#! /bin/sh

# ----- Start initialization scripts -----
~/.minoflat/scripts/tiling-common 
sxhkd &
xsetroot -cursor_name left_ptr &
polybar -r mybar &

# ----- Start user's initialization scripts -----
~/.minoflat/scripts/minoflat-init

# ----- General -----

# Set workspace name

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle  	true

# ----- Set Color ------
bspc config normal_border_color $(xrdb -query | grep background | sed s/\*\.background://ig)
bspc config active_border_color $(xrdb -query | grep background | sed s/\*\.background://ig)
bspc config focused_border_color $(xrdb -query | grep accent | sed s/\*\.accent://ig)
