#!/bin/sh

artist=$(playerctl metadata |grep xesam:artist | sed 's/.* xesam:artist *//ig')
title=$(playerctl metadata |grep xesam:title | sed 's/.* xesam:title *//ig')
stat=$(playerctl status 2> /dev/null)
artist_maxlength=30
title_maxlength=40

artist_length=$(echo $artist | wc -m)
title_length=$(echo $title | wc -m)


if [ "$artist_length" -gt $artist_maxlength ]
then
	artist_truncated=$(echo "$artist"| cut -c -"$artist_maxlength")
	artist_truncated=$(echo "$artist_truncated...")
else
	artist_truncated=$artist
fi

if [ "$title_length" -gt $title_maxlength ]
then
	title_truncated=$(echo "$title"| cut -c -"$title_maxlength")
	title_truncated=$(echo "$title_truncated...")
else
	title_truncated=$title
fi

case "$stat" in
	"Playing")
		echo "  $artist_truncated - $title_truncated"
		;;
	"Paused")
		echo "  $artist_truncated - $title_truncated"
		;;
	*)
		echo ""
		;;
esac
