#!/bin/sh

~/.minoflat/scripts/minoflat-init
ac=$(xrdb -query | grep accent | sed s/\*\.accent:\	//ig)
bg="$(xrdb -query | grep "^\*\.background" | sed s/\*\.background:\   //ig)"
fg=$(xrdb -query | grep foreground | sed s/\*\.foreground:\	//ig)
~/.minoflat/scripts/launch_dunst
exec compton --config ~/.config/picom-floating.conf &
exec plank &
exec polybar -r floating &
