#!/bin/sh

~/.minoflat/scripts/minoflat-init
ac=$(xrdb -query | grep accent | sed s/\*\.accent:\	//ig)
bg=$(xrdb -query | grep background | sed s/\*\.background:\	//ig)
fg=$(xrdb -query | grep foreground | sed s/\*\.foreground:\	//ig)
exec dunst -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "$fg" -cf "$fg" -nf "$fg" -nfr "$ac" -lfr "$ac" -hfr "$ac" &
exec compton --config ~/.config/picom-floating.conf &
exec plank &
exec polybar -r floating &
