#!/bin/sh

if [ "$1" = "-s" ]
then
	terminal=$(grep terminal-stacking ~/.config/minoflat/config | sed "s/terminal-stacking //ig")
else
terminal=$(sed "s/terminal-stacking//ig" ~/.config/minoflat/config | grep terminal-tiling | sed "s/terminal-tiling //ig")
fi

$terminal
