#!/bin/sh
ac="$(xrdb -query | grep accent | sed s/\*\.accent:\	//ig)"
bg="$(xrdb -query | grep "^\*\.background" | sed s/\*\.background:\	//ig)"
fg="$(xrdb -query | grep foreground | sed s/\*\.foreground:\	//ig)"
font="$(xrdb -query | grep sansserif | sed s/\*\.sansserif:\	//ig)"
dunst -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "$fg" -cf "$fg" -nf "$fg" -nfr "$ac" -lfr "$ac" -hfr "$ac" -font "$font 8" &
