#!/bin/sh
reload="Reload configuration"
quit="Quit"
suspend="Suspend"
reboot="Reboot"
shutdown="Shutdown"

content="$reload\n$quit\n$shutdown\n$reboot\n$suspend"
confirmation="Yes\nNo"
current_wm=$(cat /tmp/minoflat_$USER/current_wm)
session_manager=$(grep session-manager ~/.config/minoflat/config | sed "s/session-manager //ig"| sed "s/\#.*//ig")

help (){
			echo "Usage: minoflat-system-menu [OPTIONS]"
			echo "	-r: set reload command"
			echo "	-q: set quit command"
			echo "	-m: set confirmation message"
			echo "	reload,quit,shutdown,reboot,suspend: jump to confirmation dialog and do the action"
}

echoerr() { echo -e "$@" 1>&2; }

while [ -n "$1" ]; do
	case "$1" in
		-r)
			reload_command=$2
			shift;;
		-q)
			quit_command=$2
			shift;;
		-m)
			confirmation_message=$2
			shift;;
		reload)
			mode=$reload;;
		quit)
			mode=$quit;;
		suspend)
			mode=$suspend;;
		reboot)
			mode=$reboot;;
		shutdown)
			mode=$shutdown;;
		-h)
			help
			exit;;
		*)
			echo -e "\e[31mError: \e[0mUnknown parameter: $1"
			echo ""
			help
			exit;;
	esac
shift
done


if [ -z "$mode" ]
then
mode=$(echo -e $content | rofi -dmenu -i -hide-scrollbar true -p "System menu " -me-select-entry '' -me-accept-entry "MousePrimary")

fi

if [ -z "$confirmation_message" ]
then
	confirmation_message="Are you sure"
fi

if [ -z "$reload_command" ]
then
	case "$current_wm" in
		"bspwm")
			reload_command="bspc wm -r";;
		"i3")
			reload_command="i3-msg reload";;
		"openbox")
			reload_command="openbox --reconfigure";;
		*)
		reload_command="echoerr \e[31mError: \e[0mno reload command specified";;
	esac
fi
if [ -z "$quit_command" ]
then
	case "$current_wm" in
		"bspwm")
			quit_command="bspc quit";;
		"i3")
			quit_command="i3-msg reload";;
		"openbox")
			quit_command="openbox --exit";;
		*)
		quit_command="echoerr \e[31mError: \e[0mno quit command specified"
	esac

fi

case $session_manager in
	"systemd"|"logind"|"elogind")
		suspend_dest="org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.Suspend boolean:true"
		shutdown_dest="org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.PowerOff boolean:true"
		reboot_dest="org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.Reboot boolean:true"
		;;
	"consolekit")
		suspend_dest='org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.HybridSleep boolean:true'
		shutdown_dest='org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop'
		reboot_dest='org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart'
		;;
	*)
		suspend_dest='rofi -dmenu -password -columns 1 -lines 0 -p "Enter your password" -i -width 30 | sudo -S suspend'
		shutdown_dest='rofi -dmenu -password -columns 1 -lines 0 -p "Enter your password" -i -width 30 | sudo -S poweroff'
		reboot_dest='rofi -dmenu -password -columns 1 -lines 0 -p "Enter your password" -i -width 30 | sudo -S reboot'
		sudo=1
		;;
esac

if [ "$sudo" != 1 ]
then
case $mode in
	$reload)
	action=$reload_command;;
	$quit)
	action=$quit_command;;
	$suspend)
	action="dbus-send --system --print-reply --dest=$suspend_dest" ;;
	$reboot)
	action="dbus-send --system --print-reply --dest=$reboot_dest" ;;
	$shutdown)
	action="dbus-send --system --print-reply --dest=$shutdown_dest" ;;
	*)
	exit;;
esac
else
case $mode in
	$reload)
	action=$reload_command;;
	$quit)
	action=$quit_command;;
	$suspend)
	action=$suspend_dest ;;
	$reboot)
	action=$reboot_dest ;;
	$shutdown)
	action=$shutdown_dest ;;
	*)
	exit;;
esac
fi

echo $action

if [ "$mode" != "$reload" ]
then
confirm=$(echo -e $confirmation  | rofi -dmenu -i -hide-scrollbar true -p "$confirmation_message" -me-select-entry '' -me-accept-entry "MousePrimary")
else
	confirm="Yes"
fi

if [ "$confirm" == "Yes" ]
then
	if [ "$mode" == "$reload" ]
	then
	~/.minoflat/scripts/reload_xresources
	killall polybar || true
	case "$current_wm" in
		"i3"|"bspwm" )
			nohup polybar -r mybar > /dev/null &
			;;
		"openbox"| "fluxbox" )
			nohup polybar -r floating > /dev/null &
			;;
	esac
	eval $action
else
	eval $action
fi
fi
